dependencies:
- name: connections
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: redis
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 6.4.2
- alias: redis-ie
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 6.4.2
- name: orders
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: ship
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: users
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: wimo-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.36
- name: wimo-courier
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: wimo-www
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
