PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: wimo.ae
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global: {}
prow: {}

redis:
  usePassword: false
redis-ie:
  usePassword: false
ship:
  env:
    API_HOST: https://be-stg.k8.wimo.ae
    ORDERS_SERVICE: https://orders-stg.k8.wimo.ae
    WS_HOST: be-stg.k8.wimo.ae
  image:
    pullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    domain: ship-stg.k8.wimo.ae
    enabled: true
  service:
    annotations:
      fabric8.io/expose: "false"
    externalPort: 8080
    internalPort: 80
    type: ClusterIP
wimo-api:
  env:
    FE_URL: https://fe-stg.k8.wimo.ae
    MYSQL_HOST: mysql.mysql
    MYSQL_NAME: wimo
    MYSQL_USERNAME: wimo
    NODE_ENV: production
    POSTMEN_HOST: https://sandbox-api.postmen.com/v3
    REDIS_HOST: jx-redis-master
    REDIS_PORT: "6379"
    REDIS_SESSION_HOST: jx-redis-ie-master
    REDIS_SESSION_PORT: "6379"
    REDIS_STORAGE_HOST: jx-redis-ie-master
    REDIS_STORAGE_PORT: "6379"
    S3_BUCKET: wimo-app-data-stg
    S3_BUCKET_SHIP: wimo-ship-stg
    S3_BUCKET_TEMP: wimo-label-stg
    SERVER_HOST: localhost
    SERVER_PORT: "9090"
    SMS_COUNTRY_KEY: wimo
  image:
    pullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    domain: be-stg.k8.wimo.ae
    enabled: true
  service:
    annotations:
      fabric8.io/expose: "false"
    externalPort: 80
    internalPort: 3000
    type: ClusterIP
wimo-www:
  env:
    APISERVER: https://be-stg.k8.wimo.ae/
    APISERVERSTREAMING: be-stg.k8.wimo.ae
    FE_URL: localhost
    MODE: production
    REDIS_STORAGE_HOST: jx-redis-ie-master
    SERVERPATH: localhost
    environment: stg
  image:
    pullPolicy: IfNotPresent
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    domain: fe-stg.k8.wimo.ae
    enabled: true
  service:
    annotations:
      fabric8.io/expose: "false"
    externalPort: 80
    internalPort: 80
    type: ClusterIP
orders:
  env:
    AFTERSHIP_API_HOST: https://api.aftership.com/v4
    AWS_DEFAULT_REGION: ap-southeast-1
    CONNECTION_API_URL: https://connections-stg.k8.wimo.ae
    DB_CONNECTION: mongodb
    DB_DATABASE: orders
    DB_HOST: ds255754.mlab.com
    DB_PORT: "55754"
    DB_USER: wimoadmin
    ENV_SILENT: true
    EPG_BOOKING_SOAP_ACTION: http://epg.generic.booking
    EPG_HOST: https://osbtest.epg.gov.ae
    FETCHR_HOST: https://xapi.stag.fetchr.us
    NODE_ENV: production
    OLD_DB_DATABASE: wimo
    OLD_DB_HOST: postgres-postgresql.postgres
    OLD_DB_PORT: "5432"
    OLD_DB_USER: wimo
    PORT: "3333"
    POSTMEN_HOST: https://sandbox-api.postmen.com/v3
    S3_BUCKET: wimo-orders-stg
    USER_SERVICE_URL: https://users-stg.wimo.ae
    WIMO_API_URL: https://be-stg.k8.wimo.ae:3001
    WIMO_MYSQL_DBNAME: wimo
    WIMO_MYSQL_HOST: mysql.mysql
    WIMO_MYSQL_PORT: "3306"
    WIMO_MYSQL_USER: wimo
  ingress:
    enabled: true
  existingSecret: orders-staging
wimo-courier:
  env:
    API_HOST: https://be-stg.k8.wimo.ae/
    BE_SERVICE_HOST: https://be-stg.k8.wimo.ae
    WS_HOST: be-stg.k8.wimo.ae
users:
  env:
    AWS_DEFAULT_REGION: ap-southeast-1
    DB_DATABASE: users
    DB_HOST: postgres-postgresql.postgres
    DB_PORT: "5432"
    DB_USER: wimo
    ENV_SILENT: true
    FE_URL: https://ship-stg.k8.wimo.ae
    HOST: "0.0.0.0"
    NODE_ENV: production
    PORT: "3333"
    REDIS_HOST: jx-redis-master
    REDIS_PORT: "6379"
    TOKEN_EXPIRE: "86400000"
    WIMO_API_URL: https://be-stg.wimo.ae:3001
  existingSecret: users-staging
connections:
  env:
    API2CART_URL: https://api.api2cart.com/v1.1
    AWS_DEFAULT_REGION: ap-southeast-1
    CALLBACK_BASE_URL: https://orders-stg.wimo.ae
    DB_DATABASE: connections
    DB_HOST: postgres-postgresql.postgres
    DB_PORT: "5432"
    DB_USER: wimo
    ENV_SILENT: true
    HOST: "0.0.0.0"
    NODE_ENV: production
    PORT: "3333"
    POSTMEN_HOST: https://sandbox-api.postmen.com/v3
    USER_SERVICE_URL: https://users-stg.k8.wimo.ae
    WIMO_API_URL: https://be-stg.k8.wimo.ae